# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# marketing
microsoft_clarity = ""


# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`, `strawberry`.
color_theme = "dark"

# Enable users to switch between day and night mode?
day_night = true

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
font = "classic"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = ""

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a vistor shares your site on Twitter.
twitter = ""

# Diplay a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo = ""

# Enable global source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = true
highlight_languages = ["r", "python", "markdown", "org", "yaml", "rust", "docker"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/
# highlight_style = "railscast"
# highlight_style = "nord"  # For supported styles, see https://cdnjs.com/libraries/highlight.js
highlight_style = "atom-one-dark"

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = true #false

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
#date_format = "Jan 2, 2006"
date_format = "Monday, 02 Jan 2006"

#   Examples: "3:04 pm" or "15:04"
time_format = "15:04"

# Enter an optional link for booking appointments (e.g. calendly.com).
appointment_url = "https://calendly.com"

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
#   https://wowchemy.com/docs/getting-started/page-builder/
#   ======================================================
#
#   fab = companies:
#         https://fontawesome.com/icons?d=gallery&s=brands
#   fas = Common icons
#         https://fontawesome.com/icons?d=gallery&s=regular,solid
contact_links = [
  {icon = "envelope", icon_pack = "fas", name = "Mail", link = "mailto:Markus.John.Sagen@gmail.com"},
  {icon = "linkedin", icon_pack = "fab", name = "Linkedin", link = "https://www.linkedin.com/in/markussagen/"},
  {icon = "github", icon_pack = "fab", name = "Github", link = "https://github.com/markussagen"}
  ]

# Display a map.
# To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
# a map provider below.
# To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
#   https://developers.google.com/maps/documentation/javascript/get-api-key
# To use OpenStreetMap tiles, set `map = 2`.
# To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
#   https://www.mapbox.com/studio/account/tokens
# To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.

############################
## Plugins                ##
############################

# Load CSS and JS plugins
#   E.g. To load `/assets/css/custom.css`, set `plugins_css = ["custom"]`.
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_css = ["main"]
plugins_js  = ["main"]

############################
## Advanced options       ##
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

# Align the main menu to the right of the page? (true/false)
menu_align_right = true

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display comment count (if commenting enabled in config.toml)? (true/false)
comment_count = true
disable_comments = false

# Display next/previous section pager? (true/false)
section_pager = true #false
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Monday, 02 Jan 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 3
  publication_view = 3
  talk_view = 2

# Search.
[search]
  # Search provider:
  #   0: No search engine
  #   1: academia (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 1
  [search.wowchemy]
    min_length = 1
    threshold = 0.3

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false# SITE SETUP
# Documentation: https://sourcethemes.com/academic/
